// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	public "backend/internal/handler/public"
	user "backend/internal/handler/user"
	"backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: public.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/otp",
				Handler: public.OneTimePasswordHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTParser},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user",
					Handler: user.CreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/user",
					Handler: user.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/:uid",
					Handler: user.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: user.ListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user",
					Handler: user.DetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/user/password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
			}...,
		),
	)
}
